### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by shinokada** [modernish/modernish#11]
I just installed modernish and I haven't used it yet.
So I apologize if it is answered somewhere else.

It seems modernish installs files within `~/.deta` directory.

How can I make the modernish portable?
How can I make others use modernish without installing it?
What is the best way to use modernish as a library?

**Comment by McDutchie** [comment]
> It seems it installs files within `~/.deta/bin`.

That's probably because the installer didn't have write access to `/usr/local/bin`, so it looked for the first directory in your `$PATH` that it could write in, and found that. You can always specify the installation directory yourself, either by running the installer interactively, or by using the `-d` option. See [Getting started](https://github.com/modernish/modernish#getting-started) in README.md.

> How can I make the modernish portable?
> How can I make others use modernish without installing it?

There are two ways.

First, modernish can actually be used straight from the source directory, without installing. It will be slower to start, as it needs to do a number of checks every time (such as finding a good default shell) that the installer will hardcode into the library. So if you're going to use it regularly, installing is preferred.

Second, if you want to distribute a script that you wrote along with the modernish library, so that it "just works" as a self-contained package, you can use the `-B` option to install.sh to bundle a minimised copy of modernish with one or more scripts into a package directory. See [Appendix F](https://github.com/modernish/modernish#appendix-f-bundling-modernish-with-your-script) for details. This too is slower to start, but that's inevitable if we can't do any installation-time checks.

I hope this helps...

**Comment by shinokada** [comment]
Great.
Thanks for your reply.
