### ISSUE TITLE
"can write file" returns true, if file is a directory with the w bit set but without x

### ISSUE THREAD

**Issue by d630** [modernish/modernish#13]
The README says:

> can write file: True if the file's permission bits indicate that you can write to the file: for non-directories, if a w bit is set and applies to your user; for directories, both w and x.

But actually `can write file` is also true, if file is a directory and only the w bit is set:

```sh
printf %s\\n "$MSH_VERSION" "$ME $BASH_VERSION"

foo=/tmp/dir

# Expectation: Only 703 and 707 return 0
for m in 070{0..7}; do
	if sudo -- install -m "$m" -d -- "$foo"; then
		can write "$foo"
		stat --printf="%N %u %A %a $EUID,$?\n" -- "$foo"
	fi
done

> 0.17.22-dev
> modernish on bash 5.1.12(1)-release
> '/tmp/dir' 0 drwx------ 700 1000,1
> '/tmp/dir' 0 drwx-----x 701 1000,1
> '/tmp/dir' 0 drwx----w- 702 1000,0
> '/tmp/dir' 0 drwx----wx 703 1000,0
> '/tmp/dir' 0 drwx---r-- 704 1000,1
> '/tmp/dir' 0 drwx---r-x 705 1000,1
> '/tmp/dir' 0 drwx---rw- 706 1000,0
> '/tmp/dir' 0 drwx---rwx 707 1000,0

```

**Comment by McDutchie** [comment]
Errrm yes, I made a rather stupid logic error in the implementation of `can write` on shells that support `[[`, including bash.

On POSIX shells, the implementation is correct: https://github.com/modernish/modernish/blob/61b904ad23b7037c6542fe104c24f154bc35f594/bin/modernish#L2025-L2029

On bash, I wrongly thought this was equivalent: https://github.com/modernish/modernish/blob/61b904ad23b7037c6542fe104c24f154bc35f594/bin/modernish#L1823-L1824

The problem is, of course, that if `-d $2` is true and `( -w $2 && -x $2 )` is false, then it'll test for `-w $2` instead of returning false as it should.

Sorry about that. :-/

**Comment by McDutchie** [comment]
By the way @d360, thank you very much for testing modernish and reporting this bug. Please, do let me know if you encounter any further problems.
