### ISSUE TITLE
BASHPID

### ISSUE THREAD

**Issue by izabera** [modernish/modernish#2]
alternative ways to get it: https://gist.github.com/ormaaj/4713524
reading from /proc/self/stat is lighter than spawning a subshell

**Comment by McDutchie** [comment]
Thanks for the suggestion. In spite of the .bash suffix, that code is actually a ksh93-specific implementation of `$BASHPID`, using a ksh93 discipline function. In itself, that's interesting. But modernish doesn't need `$BASHPID` on ksh93 at all, because the ksh93 version of `insubshell` already has another method: it simply determines if `${.sh.subshell}` equals 0.

**Comment by McDutchie** [comment]
Another thing to remember is that ksh93 (rather buggily) implements subshells without forking. That means the bash/mksh method of comparing `$BASHPID` with `$$` does not even work on ksh93 to determine whether or not you're in a subshell, as subshells usually have the same PID as the parent shell.
