### ISSUE TITLE
`use var/arith` suffers an error

### ISSUE THREAD

**Issue by HotFusionMan** [modernish/modernish#5]
In GNU bash, version 4.4.23(1)-release (as well as the ancient version 3.2 that Apple ships) both print the following error message in response to `use var/arith` in interactive use:
```
use var/arith
Using var/arith/ops
bash: /Users/alchou/Dropbox/bin/modernish/libexec/modernish/var/arith/cmp.mm: line 79: syntax error near unexpected token `('
bash: /Users/alchou/Dropbox/bin/modernish/libexec/modernish/var/arith/cmp.mm: line 79: `	gt() { return "$(((${1?gt: needs 2 arguments})<=(${2?gt: needs 2 arguments})${3+\\[ gt: excess arguments ]}))"; }'
bash: use: initialisation of module var/arith/cmp failed with status 1
```

**Comment by McDutchie** [comment]
That's bizarre. I can't reproduce that at all, either with bash 3.2 or with bash 4.4.23, or with anything in between.

All supported bash versions have ARITHCMD so it shouldn't even be using that version in the first place, it should be eval'ing the versions on lines 63-68.

I'd say that your modernish code might be outdated, but the code in cmp.mm hasn't really changed since 2016-09-20, so I doubt that's it either. All the same, since this is still not even released yet, make sure to 'git pull' regularly.

I can think of only one possible cause. Unlike for scripts, modernish does *not* erase all aliases when initialising on interactive shells. There could be one getting in the way.

Please start a fresh bash shell and show me the output of the command `alias` *before* loading modernish. That output may allow me to debug this.

Thanks for the report!

**Comment by McDutchie** [comment]
So yeah, I was able to reproduce your exact symptoms by defining an alias called `gt` before loading the module.

The fix will be for modules to explicitly unalias all aliases conflicting with functions. I'll do that unconditionally, even for scripts, just to be on the safe side.
