### ISSUE TITLE
HEADS-UP: FreeBSD package is on its way!

### ISSUE THREAD

**Issue by 0mp** [modernish/modernish#7]
You may have a look at the review process here: https://reviews.freebsd.org/D19350

**Comment by wagnerflo** [comment]
After recently discovering this cool library, I'm planing to use in the future for any and all shell scripts of more than a few lines. (Just the trap stack makes it worthwhile IMHO). Since FreeBSD is one of my main targets have this in Ports would be great. Can I help somehow?

**Comment by 0mp** [comment]
I'm not working on the port actively at the moment, but if you'd like to finish the efforts of creating a port I'll be happy to review it.

**Comment by wagnerflo** [comment]
Thank you. Will get back to you with feedback some time next week.

**Comment by McDutchie** [comment]
Wow! Sudden interest resurgence! I thought I was the only one left. :)

In the meantime I found an abandoned shell (AT&T ksh93) and I now maintain its [only active development branch](https://github.com/ksh93/ksh), so that's been keeping me busy... but I'll have to find some time to work on modernish some more. I still do use it for all my shell scripting needs and it's serving me well, but it would, since I wrote it to scratch all my own itches.

I also fairly recently became a FreeBSD user (on my VPS) so I'll give the port a go and report back.

**Comment by 0mp** [comment]
> I also fairly recently became a FreeBSD user (on my VPS) so I'll give the port a go and report back.

Wonderful! Note: it's only available on the latest branch of the packages currently, so don't be confused if you cannot find it on the quarterly branch.
